# Generated by Django 4.2 on 2023-05-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration_card', models.CharField(max_length=15)),
                ('received_date', models.DateField()),
            ],
            options={
                'db_table': 'ration_details',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.IntegerField()),
                ('ration_card', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('hint_question', models.TextField()),
                ('hint_answer', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
